### ISSUE TITLE
Your recent refactor changed names that breaks Gorganizer

### ISSUE THREAD

**Issue by wd5gnr** [DiSiqueira/GoTree#10]
Had to revert to the version 20 days ago.

./gorganizer.go:24: undefined: gotree.GTStructure
./gorganizer.go:26: undefined: gotree.GTStructure
./gorganizer.go:38: undefined: gotree.GTStructure
./gorganizer.go:109: undefined: gotree.GTStructure
./gorganizer.go:114: undefined: gotree.PrintTree
./gorganizer.go:119: undefined: gotree.GTStructure
./ini.go:54: undefined: gotree.GTStructure
./ini.go:60: undefined: gotree.GTStructure
./ini.go:68: undefined: gotree.GTStructure
./ini.go:78: undefined: gotree.PrintTree

**Comment by d6o** [comment]
Hello @wd5gnr! 

Sorry about that and thanks for reporting!! I just released a hotfix for Gorganizer, and I hope everything is working now. 
Btw I'm rewriting Gorganizer (this is why I did this refactor on GoTree), the new version should be available until the end of the week.

I'll keep this issue open until I'm 100% sure that everything is working as intended.

One more time, thank you for your report!!
