### ISSUE TITLE
`go get` downloads the v1 (old and broken version) instead of latest (v3)

### ISSUE THREAD

**Issue by ghost** [DiSiqueira/GoTree#19]
Hi,

found this repo today, tried doing the `go get` line to add it to my project, discovered it downloads either some .a file or the pkg code for the v1 release. Not sure what is wrong with the repo, guessing a bad release setup in github or go.mod file?

Would much prefer to import your repo instead of forking the latest version to resolve this.

Thanks

**Comment by d6o** [comment]
Hey @anz-gordonj7 Thanks for reporting, I'll look into it today

**Comment by d6o** [comment]
@anz-gordonj7 fixed the problem. I forgot to update the modules file.

You can import it now with `go get -v -u github.com/disiqueira/gotree/v3`

Closing the issue, but feel free to re-open if any problem occurs.

**Comment by albertdb** [comment]
Please fix import in README.
