### ISSUE TITLE
file system tree

### ISSUE THREAD

**Issue by ghost** [DiSiqueira/GoTree#3]
wondering if it would makes sense to extend this to allow printing a file system tree ?

The reason being that i am toying with the idea to extend this lib a bit to show git status and maybe a few other things.

The idea is that you can just install it on any machine and have a decent folder view tool, along with the micro terminal IDE ( https://github.com/zyedidia/micro )

Wondering what you think..

**Comment by d6o** [comment]
I am going to close this issue. I think the library should be as simple as possible. Another library could import this one and implement a tree that prints a system tree.
