### ISSUE TITLE
Use pointers in GTStructure to allow mutation of the items before printing

### ISSUE THREAD

**Issue by jaroslaw-bochniak** [DiSiqueira/GoTree#6]
Hi,

I have just created a PR https://github.com/DiSiqueira/GoTree/pull/5 which changes items in `GTStructure` from value receiver to a pointer. This is an API breaking change so not sure if you are open for it. 

This change basically has two benefits:
- pointer reference should be more efficient for the bigger data structures
- it allows for construction of the data structure and modification of the items before actual printing is done. This is useful in cases when construction of the structure and its final state happens in different stages of the program. Thanks to pointers data can be modified without actual need of value copying entire structure.

WDYT about it? All remarks are welcomed. 

I am happy to update `README.md` as well with the usage example if you think that this PR brings any value.

**Comment by d6o** [comment]
Hey @jaroslaw-bochniak 

Thank you for your contribution! I think the change makes a lot of sense, I created this package when I was learning GO so there is a lot to be improved on it. Lets follow with the PR, when merged I'll tag the new release with a breaking change.
